---
# This playbook contains common plays that will be run on all nodes.

- name: Install cmake
  action: "{{ ansible_pkg_mgr}} name={{ item }} update_cache=yes state={{ cmake_pkg_state|default('present') }}"
  tags: package
  with_items:
   - cmake
#   - cmake-curses-gui
